-- 1. Enable Vector Physics (Safe to run multiple times)
create extension if not exists vector;

-- 2. The Particles (Stocks) - checks if table exists first
create table if not exists stocks_ohlc (
  id bigint generated by default as identity primary key,
  ticker text not null,
  date date not null,
  close numeric,
  volume numeric,
  unique(ticker, date)
);

-- 3. The Fields (News Vectors)
create table if not exists news_vectors (
  id bigint generated by default as identity primary key,
  ticker text not null,
  headline text not null,
  published_at timestamp with time zone,
  embedding vector(1536)
);

-- 4. The Bonds (Graph Edges)
create table if not exists knowledge_graph (
  id bigint generated by default as identity primary key,
  source_node text not null,
  target_node text not null,
  edge_type text not null,
  weight float default 1.0
);

-- 5. The Brain (Functions are "created or replaced", so they overwrite safely)
create or replace function hybrid_graph_search(
  query_embedding vector(1536), 
  match_threshold float, 
  match_count int
)
returns table (
  news_id bigint,
  headline text,
  similarity float,
  connected_ticker text,
  edge_type text
)
language plpgsql
as $$
begin
  return query
  with relevant_news as (
    select nv.id, nv.headline, 1 - (nv.embedding <=> query_embedding) as similarity
    from news_vectors nv
    where 1 - (nv.embedding <=> query_embedding) > match_threshold
    order by similarity desc
    limit match_count
  )
  select 
    rn.id, rn.headline, rn.similarity, kg.target_node, kg.edge_type
  from relevant_news rn
  left join knowledge_graph kg on cast(rn.id as text) = kg.source_node
  order by rn.similarity desc;
end;
$$;
